<?php

/**
 * @file
 * Contains ewp_phone_number.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ewp_phone_number_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ewp_phone_number module.
    case 'help.page.ewp_phone_number':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal implementation of the EWP Phone Number Types') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ewp_phone_number_theme() {
  return [
    'ewp_phone_number_default' => [
      'variables' => ['e164' => NULL, 'ext' => NULL, 'other_format' => NULL],
    ],
  ];
}
